const PLAYERS = [
{name:"Kylian Mbappé",country:"France",pos:"ST",rating:91,base:500,emoji:"⚡"},{name:"Erling Haaland",country:"Norway",pos:"ST",rating:91,base:500,emoji:"🧊"},
{name:"Lionel Messi",country:"Argentina",pos:"RW",rating:90,base:450,emoji:"🐐"},{name:"Cristiano Ronaldo",country:"Portugal",pos:"ST",rating:88,base:350,emoji:"👑"},
{name:"Jude Bellingham",country:"England",pos:"CM",rating:90,base:450,emoji:"💎"},{name:"Vinícius Júnior",country:"Brazil",pos:"LW",rating:90,base:450,emoji:"🔥"},
{name:"Rodri",country:"Spain",pos:"CDM",rating:91,base:450,emoji:"🧠"},{name:"Kevin De Bruyne",country:"Belgium",pos:"CM",rating:90,base:400,emoji:"🎯"},
{name:"Harry Kane",country:"England",pos:"ST",rating:90,base:400,emoji:"🎩"},{name:"Mohamed Salah",country:"Egypt",pos:"RW",rating:89,base:400,emoji:"🏹"},
{name:"Lamine Yamal",country:"Spain",pos:"RW",rating:86,base:300,emoji:"🌟"},{name:"Pedri",country:"Spain",pos:"CM",rating:86,base:250,emoji:"🪄"},
{name:"Bukayo Saka",country:"England",pos:"RW",rating:87,base:300,emoji:"🚀"},{name:"Phil Foden",country:"England",pos:"CAM",rating:88,base:320,emoji:"🎨"},
{name:"Florian Wirtz",country:"Germany",pos:"CAM",rating:88,base:320,emoji:"✨"},{name:"Jamal Musiala",country:"Germany",pos:"CAM",rating:87,base:300,emoji:"🕺"},
{name:"Federico Valverde",country:"Uruguay",pos:"CM",rating:88,base:300,emoji:"🏃"},{name:"Lautaro Martínez",country:"Argentina",pos:"ST",rating:89,base:350,emoji:"🐂"},
{name:"Antoine Griezmann",country:"France",pos:"CF",rating:88,base:300,emoji:"🦊"},{name:"Rafael Leão",country:"Portugal",pos:"LW",rating:86,base:250,emoji:"💨"},
{name:"Neymar Jr",country:"Brazil",pos:"LW",rating:87,base:300,emoji:"🎭"},{name:"Son Heung-min",country:"South Korea",pos:"LW",rating:87,base:280,emoji:"☀️"},
{name:"Virgil van Dijk",country:"Netherlands",pos:"CB",rating:89,base:350,emoji:"🧱"},{name:"Rúben Dias",country:"Portugal",pos:"CB",rating:88,base:300,emoji:"🛡️"},
{name:"William Saliba",country:"France",pos:"CB",rating:87,base:280,emoji:"🧱"},{name:"Achraf Hakimi",country:"Morocco",pos:"RB",rating:86,base:230,emoji:"🏍️"},
{name:"Theo Hernández",country:"France",pos:"LB",rating:86,base:230,emoji:"⚔️"},{name:"Trent Alexander-Arnold",country:"England",pos:"RB",rating:86,base:230,emoji:"📐"},
{name:"Alisson Becker",country:"Brazil",pos:"GK",rating:89,base:300,emoji:"🧤"},{name:"Thibaut Courtois",country:"Belgium",pos:"GK",rating:89,base:300,emoji:"🧤"},
{name:"Emiliano Martínez",country:"Argentina",pos:"GK",rating:87,base:240,emoji:"🧤"},{name:"Gianluigi Donnarumma",country:"Italy",pos:"GK",rating:87,base:240,emoji:"🧤"},
{name:"Bruno Fernandes",country:"Portugal",pos:"CAM",rating:88,base:300,emoji:"🎯"},{name:"Bernardo Silva",country:"Portugal",pos:"CM",rating:88,base:300,emoji:"🧵"},
{name:"Declan Rice",country:"England",pos:"CDM",rating:87,base:280,emoji:"🔒"},{name:"Aurélien Tchouaméni",country:"France",pos:"CDM",rating:86,base:250,emoji:"⚙️"},
{name:"Gavi",country:"Spain",pos:"CM",rating:84,base:180,emoji:"⚡"},{name:"Khvicha Kvaratskhelia",country:"Georgia",pos:"LW",rating:86,base:240,emoji:"🌀"},
{name:"Victor Osimhen",country:"Nigeria",pos:"ST",rating:87,base:280,emoji:"🦅"},{name:"Álvaro Morata",country:"Spain",pos:"ST",rating:83,base:120,emoji:"🎯"},
{name:"Nicolò Barella",country:"Italy",pos:"CM",rating:87,base:280,emoji:"🔋"},{name:"João Cancelo",country:"Portugal",pos:"RB",rating:86,base:230,emoji:"🪽"},
{name:"Mikel Merino",country:"Spain",pos:"CM",rating:84,base:160,emoji:"⚙️"},{name:"Darwin Núñez",country:"Uruguay",pos:"ST",rating:84,base:180,emoji:"💥"},
{name:"Christian Pulisic",country:"USA",pos:"RW",rating:84,base:160,emoji:"🦅"},{name:"Cody Gakpo",country:"Netherlands",pos:"LW",rating:84,base:160,emoji:"🌪️"}
];